/**
 * El Rango de IdItems de Pendiente va de
 * 841 - 880
 */
export enum PendienteIdItem
{
  PENDIENTES_DE_MADERA= 841,
  PENDIENTES_DE_COBRE= 842,
  PENDIENTES_DE_PLATA= 843,
  PENDIENTES_DE_ORO= 844,
  PENDIENTE_DE_JADE= 845,
  PENDIENTES_DE_EBANO= 846,
  PENDIENTES_DE_PERLAS= 847,
  PENDIENTES_DE_ORO_BLANCO= 848,
  PENDIENTES_DE_CRISTAL= 849,
  PENDIENTES_DE_AMATISTA= 850,
  PENDIENTES_LAGR_CIELO= 851
}