import { allFullNameBonusList } from "./bonus-list-full-name.enum";
import { BonusRefKeys } from "./ref-bonus-name.type";

/**
 * 
 * @param bonus - refrencia del bonus
 * @returns retorna el nombre completo en base a la referencia del bonus o si
 * no encuentra retorna el bonusRef
 */
export const bonusFullNameByRef = (bonus: BonusRefKeys) => {
    const REFERENCE = {
        ad: allFullNameBonusList.VALOR_DE_ATAQUE,
        animales: allFullNameBonusList.FUERZA_CONTRA_ANIMALES,
        ap: allFullNameBonusList.VALOR_DE_ATAQUE_MAGICO,
        bloquear_ataques: allFullNameBonusList.PROB_DE_BLOQUEAR_ATAQUES_BASICOS,
        bonus_estado: allFullNameBonusList.BONUS_ESTADO,
        bonus_exp: allFullNameBonusList.BONUS_EXP,
        bonus_fuego: allFullNameBonusList.BONUS_INCENDIO,
        bonus_sangrado: allFullNameBonusList.BONUS_SANGRAD,
        bonus_veneno: allFullNameBonusList.BONUS_VENENO,
        bonus_yang: allFullNameBonusList.BONUS_YANG,
        chaman: allFullNameBonusList.FUERZA_CONTRA_CHAMANES,
        chances_exp: allFullNameBonusList.PROB_DE_OBTENER_BONUS_DE_EXP,
        chances_objetos: allFullNameBonusList.PROB_DE_CAER_MAS_OBJETOS,
        chances_raros: allFullNameBonusList.AUMENTO_DE_OBJETOS_RAROS,
        chances_yang: allFullNameBonusList.FRECUENCIA_DE_YANG,
        corta_curacion: allFullNameBonusList.CORTA_CURACION,
        critico: allFullNameBonusList.PROB_DE_GOLPES_CRITICOS,
        damage_taken: allFullNameBonusList.DAMAGE_TAKEN,
        daño_critico: allFullNameBonusList.DAÑO_CRITICO,
        def: allFullNameBonusList.DEFENSA,
        def_campana: allFullNameBonusList.DEFENSA_CAMPANA,
        def_chaman: allFullNameBonusList.DEFENSA_CHAMAN,
        def_daga: allFullNameBonusList.DEFENSA_DAGA,
        def_desmayo: allFullNameBonusList.DEFENSA_CONTRA_DESMAYO,
        def_dos_manos: allFullNameBonusList.DEFENSA_DOS_MANOS,
        def_espada: allFullNameBonusList.DEFENSA_ESPADA,
        def_fan: allFullNameBonusList.DEFENSA_FAN,
        def_flecha: allFullNameBonusList.RESISTENCIA_A_FLECHAS,
        def_guerrero: allFullNameBonusList.DEFENSA_GUERRERO,
        def_hab: allFullNameBonusList.RESISTENCIA_AL_DAÑO_DE_HABILIDAD,
        def_incendio: allFullNameBonusList.RESISTENCIA_AL_FUEGO,
        def_magia: allFullNameBonusList.RESISTENCIA_MAGIA,
        def_media:allFullNameBonusList.RESISTENCIA_AL_DAÑO_DE_MEDIA,
        def_ninja: allFullNameBonusList.DEFENSA_NINJA,
        def_retardo: allFullNameBonusList.DEFENSA_CONTRA_RETARDO,
        def_sangrado: allFullNameBonusList.RESISTENCIA_AL_SANGRADO,
        def_sura: allFullNameBonusList.DEFENSA_SURA,
        def_veneno: allFullNameBonusList.RESISTENCIA_AL_VENENO,
        demonios: allFullNameBonusList.FUERZA_CONTRA_DEMONIOS,
        desmayo: allFullNameBonusList.DEFENSA_CONTRA_DESMAYO,
        DEX: allFullNameBonusList.DEX,
        doble_golpe: allFullNameBonusList.DOBLE_GOLPE,
        duracion_estado: allFullNameBonusList.DURACION_ESTADO,
        esquivar_ataques: allFullNameBonusList.ESQUIVAR_ATAQUES,
        guerrero: allFullNameBonusList.FUERZA_CONTRA_GUERREROS,
        habilidad: allFullNameBonusList.DAÑO_DE_HABILIDAD,
        hp: allFullNameBonusList.MAX_HP,
        incendio: allFullNameBonusList.OPCION_DE_INCENDIO,
        INT: allFullNameBonusList.INT,
        media: allFullNameBonusList.DAÑO_DE_MEDIA,
        medio_humanos: allFullNameBonusList.FUERZA_CONTRA_MEDIO_HUMANOS,
        misticos: allFullNameBonusList.FUERZA_CONTRA_MISTICOS,
        monstruos: allFullNameBonusList.FUERZA_CONTRA_MONSTRUOS,
        ninja: allFullNameBonusList.FUERZA_CONTRA_NINJAS,
        orcos: allFullNameBonusList.FUERZA_CONTRA_ORCOS,
        penetracion: allFullNameBonusList.PROB_DE_GOLPES_DE_PENETRACION,
        penetracion_habilidad: allFullNameBonusList.PENETRACION_HABILIDAD,
        reflectar: allFullNameBonusList.PROB_ES_DE_REFLECTAR_GOLPES_BASICOS,
        regen_hp: allFullNameBonusList.REGENERACION_DE_HP,
        retardo: allFullNameBonusList.PROB_DE_RETARDO,
        robo_vida: allFullNameBonusList.ROBO_DE_VIDA,
        sangrado: allFullNameBonusList.OPCION_DE_SANGRADO,
        STR: allFullNameBonusList.STR,
        sura: allFullNameBonusList.FUERZA_CONTRA_SURAS,
        time_reduction: allFullNameBonusList.TIME_REDUCTION,
        va: allFullNameBonusList.VELOCIDAD_DE_ATAQUE,
        vampirismo_hechizo: allFullNameBonusList.VAMPIRISMO_DE_HECHIZO,
        veneno: allFullNameBonusList.OPCION_DE_ENVENENAMIENTO,
        vh: allFullNameBonusList.VELOCIDAD_DE_HECHIZO,
        VIT: allFullNameBonusList.VIT,
        vm: allFullNameBonusList.VELOCIDAD_DE_MOVIMIENTO
    } satisfies Record<BonusRefKeys, allFullNameBonusList>

    return REFERENCE[bonus] ?? bonus
}