/**
 * El Rango de IdItems de Armadura Sura va de
 * 1 - 20
 */
export enum ArmaduraSuraIdItem
{
  ARMADURA_PLACAS_REQUIEM= 1,
  ARMADURA_PLACAS_DE_BRUJO= 2,
  ARMADURA_DE_DESGRACIA= 3,
  ARMADURA_PLACAS_FANTASMA= 4,
  ARMADURA_YIN_YANG= 5,
  ARMADURA_PLACAS_MISTICA= 6,
  ARMADURA_PLACAS_DE_NIEBLA= 7,
  ARMADURA_MASCARA_FANTASMA= 8,
  ARMADURA_PLACAS_ESPIRITU= 9,
  ARMADURA_PLACAS_MAGICA= 10
}